// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
    // show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDfXqhDBk-uP5SvBMiRI02OdGAF0wqTaXc',
  //   appId: '1:1095523962421:web:6a97841181303dd7806b7c',
  //   messagingSenderId: '1095523962421',
  //   projectId: 'college-login-firebase',
  //   authDomain: 'college-login-firebase.firebaseapp.com',
  //   databaseURL:
  //       'https://college-login-firebase-default-rtdb.europe-west1.firebasedatabase.app',
  //   storageBucket: 'college-login-firebase.appspot.com',
  //   measurementId: 'G-B5T5YGMLV9',
  // );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyC3MBiXL7oH2GNJ0UvyRl6EXldjVYAuRZQ',
  //   appId: '1:1095523962421:android:9aab1a6642f95eb6806b7c',
  //   messagingSenderId: '1095523962421',
  //   projectId: 'college-login-firebase',
  //   databaseURL:
  //       'https://college-login-firebase-default-rtdb.europe-west1.firebasedatabase.app',
  //   storageBucket: 'college-login-firebase.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCrDT5Cc3CdSZYwFUE0Y0POYHHsNGgsp9U',
  //   appId: '1:1095523962421:ios:a8ac6a2301da66f6806b7c',
  //   messagingSenderId: '1095523962421',
  //   projectId: 'college-login-firebase',
  //   databaseURL:
  //       'https://college-login-firebase-default-rtdb.europe-west1.firebasedatabase.app',
  //   storageBucket: 'college-login-firebase.appspot.com',
  //   androidClientId:
  //       '1095523962421-nsegsk2nin0rubtbfifkmrvuucpedp8m.apps.googleusercontent.com',
  //   iosClientId:
  //       '1095523962421-7shck4r1rvusth9ggf0djr7v3033mm1u.apps.googleusercontent.com',
  //   iosBundleId: 'com.college.dart.app',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyCrDT5Cc3CdSZYwFUE0Y0POYHHsNGgsp9U',
  //   appId: '1:1095523962421:ios:a8ac6a2301da66f6806b7c',
  //   messagingSenderId: '1095523962421',
  //   projectId: 'college-login-firebase',
  //   databaseURL:
  //       'https://college-login-firebase-default-rtdb.europe-west1.firebasedatabase.app',
  //   storageBucket: 'college-login-firebase.appspot.com',
  //   androidClientId:
  //       '1095523962421-nsegsk2nin0rubtbfifkmrvuucpedp8m.apps.googleusercontent.com',
  //   iosClientId:
  //       '1095523962421-7shck4r1rvusth9ggf0djr7v3033mm1u.apps.googleusercontent.com',
  //   iosBundleId: 'com.college.dart.app',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyDfXqhDBk-uP5SvBMiRI02OdGAF0wqTaXc',
  //   appId: '1:1095523962421:web:20eb28e371c14402806b7c',
  //   messagingSenderId: '1095523962421',
  //   projectId: 'college-login-firebase',
  //   authDomain: 'college-login-firebase.firebaseapp.com',
  //   databaseURL:
  //       'https://college-login-firebase-default-rtdb.europe-west1.firebasedatabase.app',
  //   storageBucket: 'college-login-firebase.appspot.com',
  //   measurementId: 'G-VGB98LFGDM',
  // );

// }
